### ISSUE TITLE
[Feature]: Too much output when end of operation

### ISSUE THREAD

**Issue by piexlmax** [selefra/selefra#1]
### Priority

Medium

### Contact Details

qimiaojiangjizhao@gmail.com

### Summary

I hope the output can help me eliminate duplicate log outputs

### Description

When I experienced selefre and ran the program according to the steps provided on the official website, I received a lot of log output. 

After checking, it was found that my AWS service did have these problems, but I received a lot of duplicate content output. 

I hope that the output content can be classified or reduced, which is more conducive to locating the problem for me.

### Benefit

It can make the information obtained by users more concise.

**Comment by FelixsJiang** [comment]
We are very happy to receive your suggestions, we will try to optimize the project.
