### ISSUE TITLE
[Feature]:  telemetry collector

### ISSUE THREAD

**Issue by monserrat101** [selefra/selefra#193]
### Priority

Critical

### Summary

x

### Description

You need to be able to know which providers are used most often

### Benefit

x

**Comment by leonynn** [comment]
Where is the associated PR?

**Comment by monserrat101** [comment]
#185

**Comment by monserrat101** [comment]
@leonynn 
You will need:
1. Acceptance confirmation is ok
2. Urge the person who wrote the document to add the corresponding document

**Comment by leonynn** [comment]
@WarrenLau1 please write doc with telemetry
