### ISSUE TITLE
[Feature]: Support docker container

### ISSUE THREAD

**Issue by leonynn** [selefra/selefra#2]
### Priority

High

### Contact Details

leon@selefra.io

### Summary

Add support for Selefra  cli docker image

### Description

Took a minute to set up. I'd recommend shipping a docker container.

reference:
https://www.reddit.com/r/selfhosted/comments/11xvqz3/comment/jd5838k/

### Benefit

Start Selefra faster to avoid complex settings affecting the first use of the product.

**Comment by leonynn** [comment]
Thanks @ddproxy for the feedback.

**Comment by FelixsJiang** [comment]
Now that we have provided the dockerfile, you can run a fully configured selefra by building a docker image locally.
