### ISSUE TITLE
[Bug]: Under the auth0 provider, the new client cannot execute the result, but the old client can

### ISSUE THREAD

**Issue by tyler0111** [selefra/selefra#203]
### Version

0.0.12

### What happened?

Under the auth0 provider, the new client cannot execute the result, but the old client can. Execute SQL in the database, also with results.

new client:

```yaml
Fetch queue done
Rule rules_exist_that_use_the_entire_contextual_object:SF160201 begin exec...
Rule users_with_unverified_mailboxes_exist:SF160101 begin exec...
Apply done
```

old client:

```yaml
Output
    Rules exist that use the entire contextual object, rule name: Adaptive MFA
Selefra exit
```

SQL:

```sql
SELECT
  *
FROM
  auth0_rule
WHERE
  script LIKE '%const % = context;%';
```

**Comment by monserrat101** [comment]
SQL check is introduced in the new CLI. The auth0 Provider uses an incorrect long name, resulting in SQL not finding the corresponding Provider for execution. The auth0 corrects the provider name by sending v0.0.8, and the corresponding prompt is added here in the CLI

**Comment by monserrat101** [comment]
#208
