### ISSUE TITLE
[Bug]: Selefra GPT functionality informs me of a syntax error.

### ISSUE THREAD

**Issue by ghost** [selefra/selefra#24]
### Version

latest

### What happened?

When I run the following command, I received an error message.

```bash
selefra gpt "Query S3 Buckets without MFA Delete Protection Enabled."
```
![image](https://github.com/selefra/selefra/assets/124039940/8331c8d3-e6a3-42f9-9ad4-362e6379451f)

**Comment by FelixsJiang** [comment]
The problem has been fixed to the main branch. Please pull the branch for testing. Thanks.
