### ISSUE TITLE
[Bug]: If DNS pollution occurs

### ISSUE THREAD

**Issue by Gopherlinzy** [selefra/selefra#5]
### Contact Details

huzhoulinyoujia@gmail.com

### Version

0.1.0

### What happened?

➜ selefra-demo (main) ✗ selefra apply
load module ./ @ /Users/admin/go/src/selefra-demo success
Login to selefra cloud main-grpc.selefra.io:1234
Selefra Cloud init success
Use built-in PostgreSQL database...
Start postgresql success
waiting for server to start.... done
server started
error[E827890]: get provider azure meta information from registry error: Get "https://raw.githubusercontent.com/selefra/registry/main/provider/azure/metadata.yaml": dial tcp 0.0.0.0:443: connect: connection refused
 -->  /Users/admin/go/src/selefra-demo/selefra.yaml:9:19 ( selefra.providers[0] )
| 4          project: selefra-demo
| 5      cli_version: 0.1.0
| 6      log_level: info
| 7      providers:
| 8          - name: azure
| 9            source: azure
|                      ^^^^^
| 10           version: v0.1.0
| 11
--> See our docs: http://selefra.io/docs

### Proposed changes

1. Query the real IP address
Through IPAddress.com query raw.githubusercontent.com real IP
185.199.108.133
185.199.109.133
185.199.110.133
185.199.111.133
2. Modify hosts
CentOS and macOS input directly from terminals
sudo vi /etc/hosts
Edit the hosts file and add the following content
(You can configure the same domain name and different ip addresses. The resolution sequence is from the first IP address. If the first IP address fails to be resolved, the next IP address will be resolved.)
185.199.110.133 [raw.githubusercontent.com](http://raw.githubusercontent.com/)
185.199.111.133 [raw.githubusercontent.com](http://raw.githubusercontent.com/)

**Comment by FelixsJiang** [comment]
Thanks a lot for the solution, but we can’t reproduce this dsn pollution issue.

We will temporarily keep this issue for reference by other people who have this problem.
